---
application:
  name: "veracitymusicplayerbot"
  project: "VeracityMusic"
  organization: "QoveryCommunity"
  storage:
  - name: "root"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/root"
routers:
- name: "main-veracitymusicplayerbot"
  routes:
  - application_name: "veracitymusicplayerbot"
    paths:
    - "/*"
